server:
  port: 7001
spring:
  application:
    name: cz-config-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:configServer
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

logging:
  level:
    root: info
    org.springframework: info

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl